### ISSUE TITLE
What does this do?

### ISSUE THREAD

**Issue by markknol** [modjke/hxmlinstall#1]
I found your lib via twitter. What does it solve?

Are you aware you can do `-lib awesomelib:git:https://github.com/user/repo.git#12345` in hxml to set a dependency from GitHub?

**Comment by modjke** [comment]
Oh boi... i'm lost for words now.
No, i was not aware of that.
Purpose of this was exactly it, set a github dependency / install it / updated references if needed.

**Comment by modjke** [comment]
Wait, what does exactly `-lib awesomelib:git:https://github.com/user/repo.git#12345` do?
Will it automaticly checkout a lib from a specified origin and commit? No, i've tested it.
Will it warn you if you are building with outdated repository? No, i've tested it.
Every build my lib is checking if a local git lib is up to date with specified commit and warns you if it is not.
It's kinda similar to https://github.com/andywhite37/hmm but works without additional json and does not require a local haxelib repo.

**Comment by markknol** [comment]
Well you can use a branch or tag. Not sure if you can use a specific commit, never tried that. No doesn't warn if out of date, but in general if you work in team you want to lock to specific tag yourself I guess. 
Atm automatic update isn't what haxelib does, you need to require one.
I now kind of understand what the library solves but I think it would be better to raise the actual problems as issue on haxelib's Github. Im glad I asked, please dont feel ashamed, just here trying to help. I think this `-lib mylib:git:..` should be documented better.

**Comment by modjke** [comment]
>  I think it would be better to raise the actual problems as issue on haxelib's Github

Well, i don't think that github hosted libs should be a part of a haxelib. lib.haxe.org should be a stable provider of high quality libs (we should encourage lib maintainers to activly update their libs). hxmlinstall is for a specific case where you left with either unsuported or bugged library or you just waiting for your pull request to be merged AND it's crucial for your project to use updated/fixed lib.

**Comment by markknol** [comment]
I tried, but you can use a specific commit, this lib pulls https://github.com/modjke/hxmlinstall/commit/b662cdf8dc60bc6e00654e3e8f3557dcb091b412 of your library. 
```
-lib mylib:git:https://github.com/modjke/hxmlinstall.git#b662cdf8dc60bc6e00654e3e8f3557dcb091b412
```

Also for pull request commits it also works. For example I have this one:
<https://github.com/HaxeFoundation/hxnodejs/pull/85>
The commit is in my git repo branch is this one
<https://github.com/markknol/hxnodejs/blob/7c4f9843dd0f6ad512906917d855c3a815f468ab/src/sys/FileSystem.hx>
So in that case I can do 
```
-lib mylib:git:https://github.com/markknol/hxnodejs.git#7c4f9843dd0f6ad512906917d855c3a815f468ab
```
So the current thing already works for crucial situations. The only thing is that it doesn't warn when out of date (I guess that's to prevent you from doing http requests on each compile, which requires you to be online)

I've [added this to the manual](https://github.com/HaxeFoundation/HaxeManual/commit/f3d9fa98a0f925c3f39740eff8892d41106df623) to make it more visible. Anyway, case closed. 👍 Have a good day!

**Comment by modjke** [comment]
Thanks, i will update my lib to support `-lib:git:url` format
